include(FetchContent)
if (TARGET fmt)
    message(WARNING "Target fmt already exists!")
else ()
    message(STATUS "path:${CMAKE_CURRENT_LIST_DIR}/fmt/fetch_fmt.cmake")
    include(${CMAKE_CURRENT_LIST_DIR}/fmt/fetch_fmt.cmake)
endif ()
if (TARGET ejson)
    message(WARNING "Target ejson already exists!")
else ()
    message(STATUS "path:${CMAKE_CURRENT_LIST_DIR}/fmt/fetch_ejson4cpp.cmake")
    include(${CMAKE_CURRENT_LIST_DIR}/ejson4cpp/fetch_ejson4cpp.cmake)
endif ()