include(FetchContent)
if (TARGET fmt)
    message(WARNING "Target fmt already exists!")
else ()
    include(./dependencies/fmt/fetch_fmt.cmake)
endif ()
if (TARGET ejson)
    message(WARNING "Target ejson already exists!")
else ()
    include(./dependencies/ejson4cpp/fetch_ejson4cpp.cmake)
endif ()